# services/pdf_generator.py
import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor
from reportlab.lib.units import mm
from extensions import db
from models.candidate import Candidate
from models.voter import Voter
from flask import current_app

class PDFGenerator:
    def __init__(self):
        pass

    def generate_result_pdf(self):
        # --- Ambil data kandidat ---
        candidates = Candidate.query.order_by(Candidate.nomor).all()

        # --- Hitung jumlah suara berdasarkan voters.vote ---
        votes_per_candidate = {
            c.id: Voter.query.filter_by(vote=c.id).count()
            for c in candidates
        }

        # --- Hitung statistik umum ---
        total_voters = Voter.query.count()
        voters_voted = Voter.query.filter_by(has_voted=True).count()
        golput = total_voters - voters_voted
        golput_percent = (golput / total_voters * 100) if total_voters else 0

        # --- Lokasi output PDF ---
        ts = datetime.now().strftime("%Y%m%d%H%M%S")
        fname = f"report_voting_{ts}.pdf"
        out_dir = current_app.config.get("UPLOAD_FOLDER")
        os.makedirs(out_dir, exist_ok=True)
        path = os.path.join(out_dir, fname)

        # --- Siapkan PDF ---
        c = canvas.Canvas(path, pagesize=A4)
        width, height = A4
        margin = 20 * mm
        y = height - margin

        # ================================
        # HEADER
        # ================================
        c.setFont("Helvetica-Bold", 18)
        c.drawString(margin, y, "LAPORAN HASIL VOTING")
        y -= 15 * mm

        c.setFont("Helvetica", 11)
        c.drawString(margin, y, f"Tanggal: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        y -= 12 * mm

        # ================================
        # STATISTIK UMUM
        # ================================
        c.setFont("Helvetica-Bold", 12)
        c.drawString(margin, y, "STATISTIK UMUM")
        y -= 7 * mm

        c.setFont("Helvetica", 10)
        c.drawString(margin, y, f"Total Pemilih : {total_voters}")
        y -= 5 * mm
        c.drawString(margin, y, f"Sudah Memilih : {voters_voted}")
        y -= 5 * mm
        c.drawString(margin, y, f"Golput        : {golput} ({golput_percent:.1f}%)")
        y -= 12 * mm

        # ================================
        # GRAFIK BAR
        # ================================
        c.setFont("Helvetica-Bold", 12)
        c.drawString(margin, y, "GRAFIK STATISTIK SUARA")
        y -= 10 * mm

        max_bar_width = 110 * mm     # lebih ideal dari 120mm
        bar_height = 6 * mm
        spacing = 8 * mm

        # Bar mulai dari 55 mm untuk tidak mepet
        bar_start_x = margin + 55 * mm

        max_votes = max(votes_per_candidate.values()) if votes_per_candidate else 1

        for cnd in candidates:
            votes = votes_per_candidate[cnd.id]
            bar_length = (votes / max_votes * max_bar_width) if max_votes else 0

            # Nama paslon (lebih rapi & dekat bar)
            c.setFont("Helvetica", 10)
            c.drawString(margin, y, f"Paslon {cnd.nomor} ({cnd.ketua} & {cnd.wakil}) : {votes}")

            # Bar chart (rapi, tidak kelewat)
            c.setFillColor(HexColor("#1C39BB"))
            c.rect(bar_start_x, y - 2, bar_length, bar_height, fill=True, stroke=False)

            y -= spacing

            if y < 60 * mm:
                c.showPage()
                y = height - margin

        y -= 5 * mm

        # ================================
        # TABEL
        # ================================
        c.setFont("Helvetica-Bold", 12)
        c.drawString(margin, y, "TABEL HASIL VOTING")
        y -= 8 * mm

        c.setFont("Helvetica-Bold", 10)
        c.drawString(margin, y, "No")
        c.drawString(margin + 20 * mm, y, "Ketua & Wakil")
        c.drawString(margin + 115 * mm, y, "Suara")
        y -= 6 * mm

        c.line(margin, y, width - margin, y)
        y -= 7 * mm

        no = 1
        c.setFont("Helvetica", 10)
        for cnd in candidates:
            if y < 30 * mm:
                c.showPage()
                y = height - margin

            c.drawString(margin, y, str(no))
            c.drawString(margin + 20 * mm, y, f"{cnd.ketua} & {cnd.wakil}")
            c.drawString(margin + 115 * mm, y, str(votes_per_candidate[cnd.id]))
            y -= 7 * mm
            no += 1

        y -= 12 * mm
        c.line(margin, y, width - margin, y)
        y -= 6 * mm

        c.setFont("Helvetica-Oblique", 9)
        c.drawString(margin, y, "Generated by E-Voting System")

        c.save()
        return path
